/**
 * Intent layer for offline chat.
 * Detects what the farmer asked and returns grounded FACTS for the LLM prompt.
 * Never speaks to the user directly — every reply is generated by the offline model.
 */
import kb from "@/assets/models/kb/bn_knowledge_base.json";
import {
  cachedWeather,
  currentUserFirstName,
  seasonTipBn,
  timeOfDayGreetingBn,
} from "@/lib/offlineNlu/retrieve";
import { recentDiagnoses } from "@/lib/offlineDb/queries";

type KbDisease = (typeof kb.diseases)[number];

export type ChatTopic = {
  crop?: CropKey;
  diseaseId?: string;
  askedForScan?: boolean;
};

export type IntentContext = {
  /** Short label for logging / prompt (e.g. "weather", "disease"). */
  intent: string;
  /** Grounding lines injected into the LLM prompt. */
  facts: string[];
  topic?: ChatTopic;
};

type CropKey = "tomato" | "potato" | "pepper";

const CROPS: Record<
  CropKey,
  { re: RegExp; nameBn: string; inBn: string; idPrefix: string }
> = {
  tomato: { re: /টমেটো|tomato/i, nameBn: "টমেটো", inBn: "টমেটোতে", idPrefix: "tomato" },
  potato: { re: /আলু|potato/i, nameBn: "আলু", inBn: "আলুতে", idPrefix: "potato" },
  pepper: {
    re: /মরিচ|ক্যাপসিকাম|pepper|capsicum/i,
    nameBn: "মরিচ",
    inBn: "মরিচে",
    idPrefix: "pepper",
  },
};

const BN_DIGITS = "০১২৩৪৫৬৭৮৯";
const toBn = (n: number | string) =>
  String(n).replace(/\d/g, (d) => BN_DIGITS[Number(d)]);

const WEEKDAYS = [
  "রবিবার",
  "সোমবার",
  "মঙ্গলবার",
  "বুধবার",
  "বৃহস্পতিবার",
  "শুক্রবার",
  "শনিবার",
];
const MONTHS = [
  "জানুয়ারি",
  "ফেব্রুয়ারি",
  "মার্চ",
  "এপ্রিল",
  "মে",
  "জুন",
  "জুলাই",
  "আগস্ট",
  "সেপ্টেম্বর",
  "অক্টোবর",
  "নভেম্বর",
  "ডিসেম্বর",
];

const RE = {
  greeting:
    /^(?:হ্যালো+|হেলো|হাই|hello|hi|hey|আসসালামু\s*আলাইকুম|সালাম|শুভ\s*(?:সকাল|দুপুর|বিকেল|সন্ধ্যা|রাত্রি)|good\s*(?:morning|afternoon|evening|night)|assalamu\s*alaikum|salam|shuvo\s*(?:sokal|dupur|bikal|sondha|ratri))(?:\s*(?:আরণ্য|aronno|ভাই|vai|bhai|বন্ধু|bondhu|স্যার|sir))?[\s!?।.,]*$/i,
  howAreYou:
    /কেমন\s*(?:আছ(?:েন|িস|ো)?|চলছে)|ভালো\s*আছেন|ভাল\s*আছেন|কি\s*খবর|কী\s*খবর|how\s*(?:are\s*you|r\s*u|is\s*it\s*going)|kemon\s*(?:acho|achen|aso)|valo\s*(?:acho|achen)|ki\s*khobor/i,
  time:
    /কয়টা\s*(?:বাজে|বাজছে|বাজল)|কটা\s*বাজে|সময়\s*(?:কত|কী|কি|বলো|জানাও)|(?:এখন\s*)?কত\s*সময়|বাজে\s*কয়টা|what\s*(?:is\s*)?(?:the\s*)?time|what\s*time\s*(?:is\s*it)?|tell\s*(?:me\s*)?(?:the\s*)?time|current\s*time|time\s*now|koyta\s*baj[ey]|kota\s*baj[ey]|koyta\s*bajse|somoy\s*kot[o]?|ekhon\s*(?:somoy|time|koyta)|time\s*(?:koto?|ki|now)|baje\s*koyta/i,
  date:
    /তারিখ|আজ\s*(?:কী|কি)\s*বার|কোন\s*বার|কী\s*বার|কি\s*বার|আজকের\s*(?:তারিখ|বার)|আজকে\s*(?:কী|কি)\s*বার|আজ\s*কত\s*তারিখ|\bdate\b|day\s*today|today'?s?\s*date|what\s*(?:day|date)|current\s*date|aj\s*(?:ki|kon)\s*bar|ajker\s*tarikh|tarikh\s*koto|aj\s*koto\s*tarikh/i,
  rain: /বৃষ্টি|বৃষ্টির|\brain(?:ing)?\b|brishti|bristi/i,
  temp:
    /তাপমাত্রা|টেম্প|টেম্পারেচার|ডিগ্রি|গরম\s*কত|ঠান্ডা\s*কত|\btemp\b|\btemperature\b|tapmatra|gorom\s*koto|thanda\s*koto/i,
  weather:
    /আবহাওয়া|আবহাওয়ার|weather|forecast|abohawa|abohaoya|রোদ|মেঘ|ঝড়|রোদের/i,
  thanks:
    /ধন্যবাদ|থ্যাংক|thank\s*(?:you)?|thanks|dhonnobad|dhanyabad|thnx/i,
  bye:
    /বিদায়|আল্লাহ\s*হাফেজ|খোদা\s*হাফেজ|bye|goodbye|পরে\s*কথা\s*হবে|see\s*you|take\s*care|allah\s*hafez|khoda\s*hafez|tata|টা\s*টা/i,
  who:
    /তুমি\s*কে|আপনি\s*কে|তোমার\s*নাম(?:\s*(?:কী|কি))?|আপনার\s*নাম(?:\s*(?:কী|কি))?|কী\s*করতে\s*পার|কি\s*করতে\s*পার|who\s*are\s*you|what\s*(?:is\s*)?your\s*name|what\s*can\s*you\s*do|who\s*made\s*you|what\s*is\s*aronno|tumi\s*ke|apni\s*ke|tomar\s*nam|apnar\s*nam|tumi\s*ki\s*korte\s*paro/i,
  yes: /^(?:হ্যাঁ|হ্যা|জি|জ্বি|হুম|ঠিক\s*আছে|আচ্ছা|ok|okay|yes)[\s!?।.]*$/i,
  no: /^(?:না|নাহ|না\s*তো|no)[\s!?।.]*$/i,
  treatAsk:
    /চিকিৎসা|কী\s*করব|কি\s*করব|করণীয়|ওষুধ|কীটনাশক|স্প্রে|প্রতিকার|সমাধান/i,
  preventAsk: /প্রতিরোধ|কিভাবে\s*ঠেকা|যাতে\s*না\s*হয়/i,
  diseaseAsk:
    /রোগ|দাগ|হলুদ|পচ|শুকি|কুঁকড়|কোঁকড়|পোকা|সমস্যা|কী\s*হয়েছে|কি\s*হয়েছে|ধ্বসা|ব্লাইট|ছত্রাক/i,
  toolsAsk:
    /যন্ত্রপাতি|হাতিয়ার|কৃষি\s*যন্ত্র|মেশিন|টুল|কোদাল|নিদানি|বেলচা|স্প্রেয়ার|ঠেলাগাড়ি|ঝাঁঝরি|দা\s*কাটারি|চাষে?\s*(?:কী|কি)\s*লাগে|(?:কী|কি)\s*লাগে/i,
  riceAsk: /ধান|আমন|বোরো|রোপা|ধান\s*চাষ/i,
};

function norm(s: string) {
  return s
    .toLowerCase()
    .replace(/[।,.!?"'«»:;()\-–—]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function firstClause(s: string) {
  return s.split(/[;।]/)[0]?.trim() ?? s;
}

function shortDiseaseName(d: KbDisease) {
  return d.diseaseNameBn
    .replace(/\(.*?\)/g, "")
    .replace(/^(?:টমেটোর|আলুর|ক্যাপসিকাম\/মরিচের|মরিচের)\s*/, "")
    .replace(/\s*রোগ$/, "")
    .trim();
}

function diseasesForCrop(crop: CropKey) {
  return kb.diseases.filter(
    (d) =>
      d.id.toLowerCase().startsWith(CROPS[crop].idPrefix) &&
      !/healthy/i.test(d.id),
  );
}

function detectCrop(text: string): CropKey | undefined {
  return (Object.keys(CROPS) as CropKey[]).find((k) => CROPS[k].re.test(text));
}

function findNamedDisease(text: string): KbDisease | undefined {
  const t = norm(text);
  return kb.diseases.find((d) => {
    if (/healthy/i.test(d.id)) return false;
    const key = norm(shortDiseaseName(d));
    return (
      (key.length >= 3 && t.includes(key)) ||
      t.includes(norm(d.diseaseNameEn))
    );
  });
}

function matchBySymptoms(text: string, crop?: CropKey): KbDisease | undefined {
  const words = norm(text).split(" ").filter((w) => w.length >= 2);
  const pool = crop
    ? diseasesForCrop(crop)
    : kb.diseases.filter((d) => !/healthy/i.test(d.id));
  let best: { d: KbDisease; score: number } | undefined;
  for (const d of pool) {
    const hay = norm(d.symptomsBn);
    const score = words.reduce(
      (s, w) => (hay.includes(w) ? s + (w.length >= 4 ? 2 : 1) : s),
      0,
    );
    if (!best || score > best.score) best = { d, score };
  }
  return best && best.score >= 4 ? best.d : undefined;
}

function formatTimeBn(now: Date) {
  const h24 = now.getHours();
  const part =
    h24 < 4
      ? "রাত"
      : h24 < 6
        ? "ভোর"
        : h24 < 12
          ? "সকাল"
          : h24 < 16
            ? "দুপুর"
            : h24 < 18
              ? "বিকেল"
              : h24 < 20
                ? "সন্ধ্যা"
                : "রাত";
  const h12 = h24 % 12 === 0 ? 12 : h24 % 12;
  const m = now.getMinutes();
  return `${part} ${toBn(h12)}টা${m ? ` ${toBn(m)} মিনিট` : ""}`;
}

function diseaseFacts(d: KbDisease, lead?: string): string {
  const name = d.diseaseNameBn.replace(/\s*\(.*?\)/g, "");
  return [
    lead ?? `যাচাইকৃত রোগ তথ্য — ${name}`,
    `লক্ষণ: ${firstClause(d.symptomsBn)}`,
    `চিকিৎসা: ${firstClause(d.treatmentBn)}`,
    `প্রতিরোধ: ${firstClause(d.preventionBn)}`,
  ].join("। ");
}

function weatherFacts(text: string): string {
  const w = cachedWeather();
  if (!w) {
    return `যাচাইকৃত আবহাওয়া: লাইভ ডেটা নেই। ঋতু পরামর্শ: ${seasonTipBn()}`;
  }
  const place = w.locationBn ? `${w.locationBn}` : "অজানা স্থান";
  const focus = RE.rain.test(text) && !RE.temp.test(text)
    ? "বৃষ্টি"
    : RE.temp.test(text) && !RE.rain.test(text)
      ? "তাপমাত্রা"
      : "সাধারণ";
  return `যাচাইকৃত আবহাওয়া (${focus}) — স্থান: ${place}; তাপমাত্রা: ${toBn(Math.round(w.tempC))}°সে; অবস্থা: ${w.conditionBn}; আর্দ্রতা: ${toBn(w.humidity)}%; বৃষ্টির সম্ভাবনা: ${toBn(Math.round(w.precipProb))}%; বৃষ্টিপাত: ${w.precipitationMm} মিমি। এই সংখ্যা হুবহু ব্যবহার করুন।`;
}

function toolsFacts(text: string): string {
  const names = kb.tools
    .slice(0, 6)
    .map((t) => t.toolNameBn.replace(/\s*\/.*$/, "").trim())
    .filter(Boolean);
  const list = names.length
    ? names.join(", ")
    : "কোদাল, বেলচা, স্প্রেয়ার, ঠেলাগাড়ি";
  if (RE.riceAsk.test(text)) {
    return `যাচাইকৃত হাতিয়ার তথ্য (ধান): কোদাল/নিদানি, বেলচা, ঝাঁঝরি/বালতি, স্প্রেয়ার, ঠেলাগাড়ি। তালিকা: ${list}।`;
  }
  return `যাচাইকৃত হাতিয়ার তথ্য: ${list}। কাজ অনুযায়ী নির্দিষ্ট হাতিয়ার বলুন।`;
}

function matchFaq(text: string): string | null {
  const t = norm(text);
  let best: { score: number; response: string } | undefined;
  for (const f of kb.faq) {
    let score = 0;
    for (const p of f.patternsBn) {
      const pn = norm(p);
      if (!pn) continue;
      if (t.includes(pn) || pn.includes(t)) score += 12;
      else {
        const words = pn.split(" ").filter((w) => w.length >= 2);
        score += words.reduce((s, w) => (t.includes(w) ? s + 1 : s), 0);
      }
    }
    if (!best || score > best.score) {
      best = { score, response: f.responseBn };
    }
  }
  return best && best.score >= 6 ? best.response : null;
}

async function cropDiseaseFacts(
  crop: CropKey,
  text: string,
): Promise<IntentContext> {
  const c = CROPS[crop];
  const bySymptom = matchBySymptoms(text, crop);
  if (bySymptom) {
    return {
      intent: "crop-disease-symptom",
      facts: [
        `উদ্দেশ্য: ${c.nameBn} রোগ।`,
        diseaseFacts(
          bySymptom,
          `লক্ষণ মিল: ${bySymptom.diseaseNameBn.replace(/\s*\(.*?\)/g, "")}`,
        ),
        "নির্দেশ: নিশ্চিত হতে পাতার ছবি স্ক্যান করতে বলুন।",
      ],
      topic: { crop, diseaseId: bySymptom.id },
    };
  }

  const recent = await recentDiagnoses(3).catch(() => []);
  const hit = recent.find(
    (r) =>
      r.labelId.toLowerCase().startsWith(c.idPrefix) &&
      !/healthy/i.test(r.labelId),
  );
  if (hit) {
    const d = kb.diseases.find((x) => x.id === hit.labelId);
    return {
      intent: "crop-recent-scan",
      facts: [
        `উদ্দেশ্য: ${c.nameBn} রোগ।`,
        `শেষ স্ক্যান: ${c.inBn} ${hit.diseaseNameBn.replace(/\s*\(.*?\)/g, "")} পাওয়া গেছে।`,
        d ? diseaseFacts(d) : "চিকিৎসা দেখতে ইতিহাসে যেতে বলুন।",
      ],
      topic: { crop, diseaseId: hit.labelId },
    };
  }

  const common = diseasesForCrop(crop).slice(0, 3).map(shortDiseaseName);
  return {
    intent: "crop-disease-ask",
    facts: [
      `উদ্দেশ্য: ${c.nameBn} রোগ জিজ্ঞাসা।`,
      `সাধারণ রোগ: ${common.join(", ")}।`,
      "নির্দেশ: লক্ষণ জিজ্ঞাসা করুন বা ছবি স্ক্যান করতে বলুন।",
    ],
    topic: { crop, askedForScan: true },
  };
}

/**
 * Resolve farmer intent → grounding facts for the offline model.
 * Does not return a user-facing reply.
 */
export async function gatherIntentContext(
  userText: string,
  ctx: { topic?: ChatTopic; hasHistory: boolean },
): Promise<IntentContext | null> {
  const text = userText.trim();
  if (!text) return null;
  const name = currentUserFirstName();

  if (RE.greeting.test(text)) {
    return {
      intent: "greeting",
      facts: [
        `উদ্দেশ্য: অভিবাদন।`,
        `অ্যাপ ডেটা: ${timeOfDayGreetingBn()}${name ? `; নাম: ${name}` : ""}${ctx.hasHistory ? "; আগের চ্যাট আছে" : ""}।`,
        "নির্দেশ: সংক্ষিপ্ত অভিবাদন দিয়ে জিজ্ঞাসা নিন কী সাহায্য লাগে (ফসল/রোগ/সার/আবহাওয়া)।",
      ],
    };
  }
  if (RE.howAreYou.test(text) && text.length < 80) {
    return {
      intent: "how-are-you",
      facts: [
        "উদ্দেশ্য: কেমন আছেন জিজ্ঞাসা।",
        "নির্দেশ: সংক্ষিপ্ত ভালো আছি বলুন, তারপর ফসলের সমস্যা আছে কিনা জিজ্ঞাসা করুন।",
      ],
    };
  }
  if (RE.time.test(text)) {
    return {
      intent: "time",
      facts: [
        "উদ্দেশ্য: সময় জিজ্ঞাসা।",
        `অ্যাপের বর্তমান ডেটা — সময়: ${formatTimeBn(new Date())}। এই মান হুবহু বলুন।`,
      ],
    };
  }
  if (RE.date.test(text) && text.length < 80) {
    const d = new Date();
    return {
      intent: "date",
      facts: [
        "উদ্দেশ্য: তারিখ/বার জিজ্ঞাসা।",
        `অ্যাপের বর্তমান ডেটা — তারিখ: ${WEEKDAYS[d.getDay()]}, ${toBn(d.getDate())} ${MONTHS[d.getMonth()]} ${toBn(d.getFullYear())}। এই মান হুবহু বলুন।`,
      ],
    };
  }
  if (RE.thanks.test(text) && text.length < 80) {
    return {
      intent: "thanks",
      facts: [
        "উদ্দেশ্য: ধন্যবাদ।",
        "নির্দেশ: সংক্ষিপ্ত কৃতজ্ঞতা স্বীকার করুন; আর কিছু জানতে চাইলে বলতে বলুন।",
      ],
    };
  }
  if (RE.bye.test(text) && text.length < 80) {
    return {
      intent: "bye",
      facts: [
        "উদ্দেশ্য: বিদায়।",
        `নির্দেশ: সংক্ষিপ্ত বিদায়${name ? ` (${name})` : ""}; প্রয়োজনে আবার কথা বলতে বলুন।`,
      ],
    };
  }
  if (RE.who.test(text) && text.length < 80) {
    return {
      intent: "identity",
      facts: [
        "উদ্দেশ্য: পরিচয় জিজ্ঞাসা।",
        "যাচাইকৃত পরিচয়: আরণ্য — অফলাইন কৃষি সহায়ক; রোগ চেনা, চিকিৎসা, আবহাওয়া ও চাষের পরামর্শ।",
      ],
    };
  }
  if (
    (RE.rain.test(text) || RE.temp.test(text) || RE.weather.test(text)) &&
    !RE.diseaseAsk.test(text)
  ) {
    return {
      intent: "weather",
      facts: ["উদ্দেশ্য: আবহাওয়া।", weatherFacts(text)],
    };
  }
  if (RE.toolsAsk.test(text)) {
    return {
      intent: "tools",
      facts: ["উদ্দেশ্য: কৃষি হাতিয়ার।", toolsFacts(text)],
    };
  }
  if (RE.riceAsk.test(text) && /হলুদ|রোগ|পাতা|পোকা|শুকি/i.test(text)) {
    return {
      intent: "rice-yellow",
      facts: [
        "উদ্দেশ্য: ধানের পাতা হলুদ/রোগ।",
        "যাচাইকৃত পরামর্শ: নাইট্রোজেন (ইউরিয়া) ঘাটতি বা পানি জমে নিকাশ সমস্যা দেখুন; নালা খুলুন; ইউরিয়া ভাগ করে দিন; পোকা/দাগ হলে কৃষি অফিস। টমেটো-আলু স্ক্যান দিয়ে ধানের রোগ নিশ্চিত হয় না।",
      ],
    };
  }

  const topicDisease = ctx.topic?.diseaseId
    ? kb.diseases.find((d) => d.id === ctx.topic?.diseaseId)
    : undefined;
  if (
    topicDisease &&
    RE.treatAsk.test(text) &&
    !detectCrop(text) &&
    !findNamedDisease(text)
  ) {
    return {
      intent: "topic-treatment",
      facts: [
        "উদ্দেশ্য: আগের রোগের চিকিৎসা।",
        diseaseFacts(topicDisease, "পূর্ববর্তী বিষয়ের রোগ"),
      ],
      topic: ctx.topic,
    };
  }
  if (topicDisease && RE.preventAsk.test(text) && !detectCrop(text)) {
    return {
      intent: "topic-prevention",
      facts: [
        "উদ্দেশ্য: আগের রোগের প্রতিরোধ।",
        `প্রতিরোধ: ${topicDisease.preventionBn}`,
      ],
      topic: ctx.topic,
    };
  }
  if (ctx.topic?.askedForScan && RE.yes.test(text)) {
    return {
      intent: "scan-confirm-yes",
      facts: [
        "উদ্দেশ্য: স্ক্যান করতে রাজি।",
        "নির্দেশ: ক্যামেরা বোতাম চাপতে বলুন; আক্রান্ত পাতার স্পষ্ট ছবি তুলতে বলুন।",
      ],
      topic: { ...ctx.topic, askedForScan: false },
    };
  }
  if (ctx.topic?.askedForScan && RE.no.test(text)) {
    return {
      intent: "scan-confirm-no",
      facts: [
        "উদ্দেশ্য: স্ক্যান করতে রাজি নন।",
        "নির্দেশ: লক্ষণ (রঙ/দাগ/পোকা) জিজ্ঞাসা করুন; নিশ্চিত না হলে স্ক্যান পরামর্শ দিন।",
      ],
      topic: ctx.topic,
    };
  }

  const faqHit = matchFaq(text);
  if (faqHit) {
    return {
      intent: "faq",
      facts: ["উদ্দেশ্য: সাধারণ FAQ।", `যাচাইকৃত উত্তর তথ্য: ${faqHit}`],
    };
  }

  const named = findNamedDisease(text);
  if (named) {
    return {
      intent: "named-disease",
      facts: ["উদ্দেশ্য: নির্দিষ্ট রোগ।", diseaseFacts(named)],
      topic: { crop: detectCrop(named.id), diseaseId: named.id },
    };
  }
  const crop = detectCrop(text);
  if (crop && RE.diseaseAsk.test(text)) {
    return cropDiseaseFacts(crop, text);
  }
  if (RE.diseaseAsk.test(text)) {
    const bySymptom = matchBySymptoms(text);
    if (bySymptom) {
      return {
        intent: "symptom-disease",
        facts: [
          "উদ্দেশ্য: লক্ষণ থেকে রোগ অনুমান।",
          diseaseFacts(
            bySymptom,
            `লক্ষণ মিল: ${bySymptom.diseaseNameBn.replace(/\s*\(.*?\)/g, "")}`,
          ),
          "নির্দেশ: ফসলের নাম ও ছবি চাইলে আরও নিশ্চিত বলতে পারবেন।",
        ],
        topic: { diseaseId: bySymptom.id },
      };
    }
  }

  return null;
}

/** @deprecated — use gatherIntentContext; kept for any leftover imports */
export async function answerByIntent(
  userText: string,
  ctx: { topic?: ChatTopic; hasHistory: boolean },
): Promise<{ text: string; topic?: ChatTopic } | null> {
  const hit = await gatherIntentContext(userText, ctx);
  if (!hit) return null;
  return { text: hit.facts.join(" "), topic: hit.topic };
}

/** Clock/calendar facts only (also covered by gatherIntentContext). */
export function clockFactsForPrompt(userText: string): string[] {
  const text = userText.trim();
  if (!text) return [];
  const wantsTime = RE.time.test(text);
  const wantsDate = RE.date.test(text) && text.length < 80;
  if (!wantsTime && !wantsDate) return [];
  const d = new Date();
  const parts: string[] = [];
  if (wantsTime) parts.push(`সময়: ${formatTimeBn(d)}`);
  if (wantsDate) {
    parts.push(
      `তারিখ: ${WEEKDAYS[d.getDay()]}, ${toBn(d.getDate())} ${MONTHS[d.getMonth()]} ${toBn(d.getFullYear())}`,
    );
  }
  return [
    `অ্যাপের বর্তমান ডেটা — ${parts.join("; ")}। এই মান হুবহু ব্যবহার করুন; নতুন সময়/তারিখ বানাবেন না।`,
  ];
}
