/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
          50: "#F0FDFA",
          100: "#D5F3EC",
          200: "#B7E6DA",
          300: "#7DCCB8",
          400: "#3AAB90",
          500: "#14967A",
          600: "#12866E",
          700: "#0F766E",
          800: "#115E59",
          900: "#134E4A",
          950: "#042F2E",
        },
        secondary: {
          DEFAULT: "rgb(var(--color-secondary) / <alpha-value>)",
          soft: "#F3FAF8",
          strong: "#C5E4DB",
        },
        tertiary: {
          DEFAULT: "#14967A",
          soft: "#E7F5F2",
          strong: "#0F766E",
        },
        harvest: {
          DEFAULT: "#B7791F",
          soft: "rgb(var(--color-harvest-soft) / <alpha-value>)",
          strong: "#8C5E14",
        },
        neutral: {
          DEFAULT: "rgb(var(--color-neutral) / <alpha-value>)",
          50: "rgb(var(--color-neutral) / <alpha-value>)",
          100: "rgb(var(--color-neutral-100) / <alpha-value>)",
          200: "rgb(var(--color-neutral-200) / <alpha-value>)",
          300: "rgb(var(--color-neutral-300) / <alpha-value>)",
          400: "rgb(var(--color-neutral-400) / <alpha-value>)",
          500: "#5C6E68",
          600: "#4B5563",
          700: "#374151",
          800: "#1F2937",
          900: "#13241F",
        },
        // Aliases used across existing components
        forest: {
          50: "#F0FDFA",
          100: "#D5F3EC",
          200: "#B7E6DA",
          300: "#7DCCB8",
          400: "#3AAB90",
          500: "#14967A",
          600: "#12866E",
          700: "#0F766E",
          800: "#115E59",
          900: "#134E4A",
        },
        leaf: {
          100: "#ECFDF5",
          300: "#6EE7B7",
          400: "#34D399",
          500: "#10B981",
        },
        soil: {
          50: "#F9FAFB",
          100: "#F3F4F6",
          200: "#E5E7EB",
          300: "#D1D5DB",
          500: "#6B7280",
          700: "#374151",
        },
        sand: "rgb(var(--color-sand) / <alpha-value>)",
        ink: "rgb(var(--color-ink) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        card: "rgb(var(--color-card) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        accent: {
          DEFAULT: "rgb(var(--color-accent) / <alpha-value>)",
          soft: "#E7F5F2",
          strong: "#0F766E",
        },
        severity: {
          low: "#047857",
          "low-bg": "#D1FAE5",
          medium: "#B54708",
          "medium-bg": "#FCEFDF",
          high: "#B42318",
          "high-bg": "#FCE8E6",
        },
      },
      fontFamily: {
        bengali: ["NotoSansBengali_400Regular"],
        "bengali-medium": ["NotoSansBengali_500Medium"],
        "bengali-semibold": ["NotoSansBengali_600SemiBold"],
        "bengali-bold": ["NotoSansBengali_700Bold"],
      },
      fontSize: {
        caption: ["15px", { lineHeight: "22px" }],
        body: ["18px", { lineHeight: "28px" }],
        "body-lg": ["20px", { lineHeight: "30px" }],
        title: ["24px", { lineHeight: "32px" }],
        display: ["32px", { lineHeight: "40px" }],
        hero: ["40px", { lineHeight: "48px" }],
      },
      minHeight: {
        touch: "52px",
        "touch-lg": "64px",
      },
      borderRadius: {
        card: "16px",
      },
    },
  },
  plugins: [],
};
